version: '3.8'

services:
# Premier service db pour la base de donnees postgres
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME} #prend la valeur DB_NAME dans le fichier .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django_network

  web:
    image: eliejah426/memoiretest1:latest1
    container_name: django_app
    command: gunicorn memoire.wsgi:application --bind 0.0.0.0:80
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge